### ISSUE TITLE
Arg `limit` is not optional

### ISSUE THREAD

**Issue by PiRomant** [gsmith257-cyber/CrookedConfluence#1]
Running without limit argument causes an error:

```py
Traceback (most recent call last):
  File "...\CrookedConfluence\CrookedConfluence.py", line 201, in <module>
    main()
  File "...\CrookedConfluence\CrookedConfluence.py", line 197, in main
    searchKeyWords(dict_path, access_token, cURL, default_headers, limit)
                                                                   ^^^^^
UnboundLocalError: cannot access local variable 'limit' where it is not associated with a value
```

**Comment by gsmith257-cyber** [comment]
Hey @PiRomant,

Thanks for pointing out this issue. My most recent commit contains a fix for this issue.

Thanks,
Grant
